# ----
# Site

title: "Leita"
url: "https://bhediathewolf.github.io"
baseurl:
google_analytics_key: "UA-98353480-1"
google_maps_javascript_api_key:
disqus_shortname: "bhedia"
addthis: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Let's get crazy!"
author:
  name: "Sannidhya Sandheer"
  email: bhediathewolf@gmail.com
  twitter: _bhedia_
social:
  name: Leita
  links:
    - https://bhediathewolf.github.io/

# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor

paginate: 10
paginate_path: "/blog/:num/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: "true"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: "project"
    values:
      layout: "project"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Twitter
  - YouTube
  - Email
  - RSS

# ---
# _comments:
#   description: Text shown when sharing on social media
#   blurb: Short bio or description of this person
